
name: docker_cd/ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1        
      - name: BooksService_cd/ci
        uses: docker/build-push-action@v2
        with:
          context: ./servizi/BookServiceITS/BookServiceITS
          file: ./servizi/BookServiceITS/BookServiceITS/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bookserviceits:latest
    
